DELETE FROM Pokemon;
DBCC CHECKIDENT ('Pokemon', RESEED, 0);
INSERT INTO [Pokemon] ([PKMN_Species], [PKMN_Type1], [PKMN_Type2], [PKMN_Ability]) VALUES
    ('Landorus-Therian', 'Ground', 'Flying', 'Intimidate'),
    ('Urshifu-Rapid-Strike', 'Fighting', 'Water', 'Unseen Fist'),
    ('Flutter Mane', 'Ghost', 'Fairy', 'Protosynthesis'),
    ('Chien-Pao', 'Dark', 'Ice', 'Sword of Ruin'),
    ('Amoonguss', 'Grass', 'Poison', 'Regenerator'),
    ('Iron Hands', 'Fighting', 'Electric', 'Quark Drive'),
    ('Heatran', 'Fire', 'Steel', 'Flash Fire'),
    ('Dragapult', 'Dragon', 'Ghost', 'Clear Body'),
    ('Rillaboom', 'Grass', NULL, 'Grassy Surge'),
    ('Farigiraf', 'Normal', 'Psychic', 'Armor Tail'),
    ('Ursaluna', 'Ground', 'Normal', 'Guts'),
    ('Cresselia', 'Psychic', NULL, 'Levitate'),
    ('Dragonite', 'Dragon', 'Flying', 'Inner Focus'),
    ('Urshifu-Single-Strike', 'Fighting', 'Dark', 'Unseen Fist'),
    ('Miraidon', 'Electric', 'Dragon', 'Hadron Engine'),
    ('Ogerpon-Hearthflame', 'Grass', 'Fire', 'Mold Breaker'),
    ('Whimsicott', 'Grass', 'Fairy', 'Prankster'),
    ('Landorus-Incarnate', 'Ground', 'Flying', 'Sheer Force'),
    ('Iron Valiant', 'Fairy', 'Fighting', 'Quark Drive'),
    ('Pelipper', 'Water', 'Flying', 'Drizzle'),
    ('Calyrex-Ice', 'Psychic', 'Ice', 'As One (Glastrier)'),
    ('Zamazenta-Crowned', 'Fighting', 'Steel', 'Dauntless Shield'),
    ('Entei', 'Fire', NULL, 'Inner Focus'),
    ('Brute Bonnet', 'Grass', 'Dark', 'Protosynthesis'),
    ('Lunala', 'Ghost', 'Psychic', 'Shadow Shield'),
    ('Chi-Yu', 'Dark', 'Fire', 'Beads of Ruin'),
    ('Koraidon', 'Fighting', 'Dragon', 'Orichalum Pulse'),
    ('Raging Bolt', 'Electric', 'Dragon', 'Protosynthesis'),
    ('Calyrex-Shadow', 'Psychic', 'Ghost', 'As One'),
    ('Incineroar', 'Fire', 'Dark', 'Intimidate'),
    ('Smeargle', 'Normal', NULL, 'Moody');
